# Generated by Django 3.1.2 on 2020-10-22 06:27

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.AddField(
            model_name='homepage',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='config',
            field=models.CharField(default='default_config', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Post date'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='page head title', required=True)), ('content', wagtail.core.blocks.TextBlock(help_text='page description', required=True))], blank=True, null=True)), ('user', wagtail.core.blocks.StructBlock([('first_name', wagtail.core.blocks.CharBlock(help_text='first name', required=True)), ('user_email', wagtail.core.blocks.CharBlock(help_text='user email', required=True)), ('surname', wagtail.core.blocks.TextBlock(help_text='Add your bio', required=True)), ('photo', wagtail.images.blocks.ImageChooserBlock()), ('role', wagtail.core.blocks.CharBlock(help_text='User Role', required=True))], blank=True, icon='user', null=True))]),
        ),
    ]
