# Generated by Django 3.1.2 on 2020-11-03 02:49

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('wagtailimages', '0022_uploadedimage'),
        ('home', '0005_auto_20201022_0627'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdeviPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True, verbose_name='Post date')),
                ('body', models.CharField(default='default_config', max_length=255)),
                ('content', wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='page head title', required=True)), ('content', wagtail.core.blocks.TextBlock(help_text='page description', required=True))], blank=True, null=True)), ('user', wagtail.core.blocks.StructBlock([('first_name', wagtail.core.blocks.CharBlock(help_text='first name', required=True)), ('user_email', wagtail.core.blocks.CharBlock(help_text='user email', required=True)), ('surname', wagtail.core.blocks.TextBlock(help_text='Add your bio', required=True)), ('photo', wagtail.images.blocks.ImageChooserBlock()), ('role', wagtail.core.blocks.CharBlock(help_text='User Role', required=True))], blank=True, icon='user', null=True))])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='author',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='config',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='content',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='date',
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.CreateModel(
            name='AdeviGalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='home.adevipage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
